apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp/optimal/pg
    server: 10.211.55.4
